[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyrcs"
version = "1.2.0"
description = "An open-source tool for collecting railway codes used in different UK rail industry systems."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Qian Fu" }
]
keywords = [
    "Python",
    "Railway",
    "Railway Codes",
    "Bridges",
    "Computer Reservation System",
    "CRS",
    "National Location Codes",
    "NLC",
    "Timing Point Locations",
    "TIPLOC",
    "Station Number Names",
    "STANME",
    "Station Numbers",
    "STANOX",
    "Electrification",
    "Engineer's Line References",
    "ELR",
    "Mileage",
    "Line Of Route",
    "LOR",
    "Railway Line Names",
    "Railway Bridges",
    "Stations",
    "Signal Boxes",
    "Tunnels",
    "Viaducts",
    "Depots",
    "Tracks"
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Topic :: Education",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux"
]
dependencies = [
    "pyhelpers ~= 2.5.0",
    "beautifulsoup4",
    "requests",
    "pandas",
]

[project.urls]
Homepage = "https://github.com/mikeqfu/pyrcs"
Documentation = "https://pyrcs.readthedocs.io/en/latest/"
Repository = "https://github.com/mikeqfu/pyrcs"
"Bug Tracker" = "https://github.com/mikeqfu/pyrcs/issues"
Changelog = "https://github.com/mikeqfu/pyrcs/blob/master/CHANGELOG.md"


# -----------------------
# Local developer tooling
# -----------------------
[dependency-groups]
dev = [
    "notebook",
    "jsonschema[format]",
    "rfc3987-syntax",
]
docs = [
    "sphinx",
    "furo",
    "sphinx-copybutton",
    "sphinx-new-tab-link",
    "sphinx-toggleprompt"
]
test = [
    "pytest",
    "coverage",
    "pytest-cov",
    "pytest-mock",
    "pytest-xdist"
]


# --------------------
# Build configuration
# --------------------
[tool.hatch.build]
artifacts = [
    "pyrcs/data/**/*"
]

[tool.hatch.build.targets.sdist]
include = [
    "pyrcs",
    "pyproject.toml",
    "CHANGELOG.md",
    "CITATION.cff",
    "LICENSE",
    "README.md"
]
exclude = [
    ".venv",
    "docs",
    "tests",
    "tutorials"
]

[tool.hatch.build.targets.wheel]
packages = ["pyrcs"]

[tool.hatch.build.targets.wheel.force-include]
"pyproject.toml" = "pyrcs/pyproject.toml"

# Custom metadata section
[tool.custom.metadata]
funder = ""
project_start = "August 2019"
corresponding_author = [
    { name = "Qian Fu", affiliation = "Birmingham Energy Institute, University of Birmingham", email = "q.fu@bham.ac.uk" },
]


# --------------------
# Pytest configuration
# --------------------
[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
addopts = [
    "-v",
    "-ra",
    "--strict-markers",
    "--strict-config",
    "--cov=pyrcs",
    "--cov-report=term-missing",
    "--cov-report=xml",
    "--cov-report=html",
    "-n",
    "auto"
]
xfail_strict = true

filterwarnings = [
    "error",
    "ignore:Support for class-based `config` is deprecated:UserWarning",
    "ignore:distutils Version classes are deprecated:DeprecationWarning",
]

# ----------------------
# Coverage configuration
# ----------------------
[tool.coverage.run]
source = ["pyrcs"]
branch = true
parallel = true
relative_files = true

[tool.coverage.paths]
source = [
    "pyrcs",
    "*/site-packages/pyrcs",
    "*/pyrcs",
]

[tool.coverage.report]
fail_under = 85
show_missing = true
exclude_also = [
    "def __repr__",
    "if TYPE_CHECKING:",
    "@overload",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]

# Report destinations
[tool.coverage.xml]
output = "reports/coverage.xml"

[tool.coverage.html]
directory = "reports/htmlcov"

