name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
      - develop
  release:
    types:
      - published

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    environment: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/source/requirements.txt
      - name: Build documentation
        run: |
          cd docs
          make html
      - name: Disable Jekyll
        run: |
          touch docs/build/html/.nojekyll
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
